"""Tests for the Production catalogue API (`/api/v1/productions`).

These tests exercise the real database (see `conftest.py`): a reachable
PostgreSQL instance is required (e.g. `podman compose up -d postgres`).
"""

import uuid

import pytest


async def _create(client, **overrides) -> dict:
    payload = {"title": "Default Test Production", **overrides}
    response = await client.post("/api/v1/productions", json=payload)
    assert response.status_code == 201, response.text
    return response.json()


# --- Creation and validation -------------------------------------------------


@pytest.mark.asyncio
async def test_create_with_only_title(client_factory):
    async with client_factory() as client:
        body = await _create(client, title="Impro Night Berlin")

    assert body["title"] == "Impro Night Berlin"
    assert body["slug"] == "impro-night-berlin"
    for field in (
        "description",
        "work_title",
        "creator_names",
        "company_name",
        "director_name",
        "venue_name",
        "city",
        "country_code",
        "premiere_date",
        "closing_date",
    ):
        assert body[field] is None
    assert uuid.UUID(body["id"])
    assert body["created_at"]
    assert body["updated_at"]


@pytest.mark.asyncio
async def test_create_with_all_fields(client_factory):
    payload = {
        "title": "Hamlet",
        "slug": "hamlet-schaubuehne-berlin",
        "description": "A staging of Shakespeare's tragedy.",
        "work_title": "Hamlet",
        "creator_names": "William Shakespeare",
        "company_name": "Schaubuehne",
        "director_name": "Example Director",
        "venue_name": "Schaubuehne am Lehniner Platz",
        "city": "Berlin",
        "country_code": "de",
        "premiere_date": "2026-03-10",
        "closing_date": "2026-05-18",
    }
    async with client_factory() as client:
        response = await client.post("/api/v1/productions", json=payload)

    assert response.status_code == 201
    body = response.json()
    assert body["slug"] == "hamlet-schaubuehne-berlin"
    assert body["country_code"] == "DE"  # normalized to uppercase
    assert body["premiere_date"] == "2026-03-10"
    assert body["closing_date"] == "2026-05-18"


@pytest.mark.asyncio
async def test_slug_is_autogenerated_from_title(client_factory):
    async with client_factory() as client:
        body = await _create(client, title="Hannah Gadsby: Woof!")

    assert body["slug"] == "hannah-gadsby-woof"


@pytest.mark.asyncio
async def test_blank_title_is_rejected(client_factory):
    async with client_factory() as client:
        response = await client.post("/api/v1/productions", json={"title": "   "})

    assert response.status_code == 422


@pytest.mark.asyncio
async def test_closing_date_before_premiere_date_is_rejected(client_factory):
    payload = {
        "title": "Broken Dates",
        "premiere_date": "2026-06-01",
        "closing_date": "2026-05-01",
    }
    async with client_factory() as client:
        response = await client.post("/api/v1/productions", json=payload)

    assert response.status_code == 422


@pytest.mark.asyncio
async def test_invalid_country_code_is_rejected(client_factory):
    async with client_factory() as client:
        response = await client.post(
            "/api/v1/productions", json={"title": "Bad Country", "country_code": "DEU"}
        )

    assert response.status_code == 422


@pytest.mark.asyncio
async def test_blank_optional_strings_are_normalized_to_null(client_factory):
    async with client_factory() as client:
        body = await _create(client, title="Blank Fields", venue_name="   ", city="")

    assert body["venue_name"] is None
    assert body["city"] is None


# --- Slugs --------------------------------------------------------------------


@pytest.mark.asyncio
async def test_get_production_by_slug(client_factory):
    async with client_factory() as client:
        created = await _create(client, title="Retrieve By Slug")
        response = await client.get(f"/api/v1/productions/slug/{created['slug']}")

    assert response.status_code == 200
    assert response.json()["id"] == created["id"]


@pytest.mark.asyncio
async def test_explicit_slug_is_honored(client_factory):
    async with client_factory() as client:
        body = await _create(client, title="Custom Slug Production", slug="my-custom-slug")

    assert body["slug"] == "my-custom-slug"


@pytest.mark.asyncio
async def test_duplicate_explicit_slug_returns_409(client_factory):
    async with client_factory() as client:
        await _create(client, title="Original", slug="shared-slug")
        response = await client.post(
            "/api/v1/productions", json={"title": "Different Title", "slug": "shared-slug"}
        )

    assert response.status_code == 409


@pytest.mark.asyncio
async def test_slug_collisions_use_deterministic_numeric_suffixes(client_factory):
    async with client_factory() as client:
        first = await _create(client, title="Hamlet")
        second = await _create(client, title="Hamlet")
        third = await _create(client, title="Hamlet")

    assert first["slug"] == "hamlet"
    assert second["slug"] == "hamlet-2"
    assert third["slug"] == "hamlet-3"


@pytest.mark.asyncio
async def test_slug_remains_stable_when_title_changes(client_factory):
    async with client_factory() as client:
        created = await _create(client, title="Original Title")
        response = await client.patch(
            f"/api/v1/productions/{created['id']}", json={"title": "A Brand New Title"}
        )

    assert response.status_code == 200
    body = response.json()
    assert body["title"] == "A Brand New Title"
    assert body["slug"] == created["slug"]


@pytest.mark.asyncio
async def test_slug_changes_only_when_explicitly_updated(client_factory):
    async with client_factory() as client:
        created = await _create(client, title="Slug Change Target")
        response = await client.patch(
            f"/api/v1/productions/{created['id']}", json={"slug": "explicitly-new-slug"}
        )

    assert response.status_code == 200
    assert response.json()["slug"] == "explicitly-new-slug"


# --- CRUD -----------------------------------------------------------------


@pytest.mark.asyncio
async def test_list_productions(client_factory):
    async with client_factory() as client:
        await _create(client, title="Alpha Show")
        await _create(client, title="Beta Show")
        response = await client.get("/api/v1/productions")

    assert response.status_code == 200
    body = response.json()
    assert body["total"] == 2
    assert len(body["items"]) == 2


@pytest.mark.asyncio
async def test_retrieve_by_uuid(client_factory):
    async with client_factory() as client:
        created = await _create(client, title="Retrieve By UUID")
        response = await client.get(f"/api/v1/productions/{created['id']}")

    assert response.status_code == 200
    assert response.json()["id"] == created["id"]


@pytest.mark.asyncio
async def test_partial_update_leaves_omitted_fields_unchanged(client_factory):
    async with client_factory() as client:
        created = await _create(client, title="Partial Update", city="Berlin", country_code="DE")
        response = await client.patch(
            f"/api/v1/productions/{created['id']}", json={"city": "Munich"}
        )

    assert response.status_code == 200
    body = response.json()
    assert body["city"] == "Munich"
    assert body["country_code"] == "DE"  # untouched


@pytest.mark.asyncio
async def test_explicit_null_clears_optional_field(client_factory):
    async with client_factory() as client:
        created = await _create(client, title="Clear Field", venue_name="Some Venue")
        response = await client.patch(
            f"/api/v1/productions/{created['id']}", json={"venue_name": None}
        )

    assert response.status_code == 200
    assert response.json()["venue_name"] is None


@pytest.mark.asyncio
async def test_delete_production(client_factory):
    async with client_factory() as client:
        created = await _create(client, title="To Be Deleted")
        delete_response = await client.delete(f"/api/v1/productions/{created['id']}")
        get_response = await client.get(f"/api/v1/productions/{created['id']}")

    assert delete_response.status_code == 204
    assert get_response.status_code == 404


@pytest.mark.asyncio
async def test_get_returns_404_for_missing_production(client_factory):
    async with client_factory() as client:
        response = await client.get(f"/api/v1/productions/{uuid.uuid4()}")

    assert response.status_code == 404


@pytest.mark.asyncio
async def test_get_returns_422_for_malformed_uuid(client_factory):
    async with client_factory() as client:
        response = await client.get("/api/v1/productions/not-a-uuid")

    assert response.status_code == 422


@pytest.mark.asyncio
async def test_get_by_slug_returns_404_for_missing_slug(client_factory):
    async with client_factory() as client:
        response = await client.get("/api/v1/productions/slug/does-not-exist")

    assert response.status_code == 404


# --- Search and filtering ------------------------------------------------


@pytest.mark.asyncio
async def test_search_matches_title(client_factory):
    async with client_factory() as client:
        await _create(client, title="Unique Searchable Title")
        await _create(client, title="Something Else")
        response = await client.get("/api/v1/productions", params={"search": "searchable"})

    body = response.json()
    assert body["total"] == 1
    assert body["items"][0]["title"] == "Unique Searchable Title"


@pytest.mark.asyncio
async def test_search_matches_work_title(client_factory):
    async with client_factory() as client:
        await _create(client, title="Show A", work_title="Distinctive Work Title")
        await _create(client, title="Show B")
        response = await client.get("/api/v1/productions", params={"search": "distinctive work"})

    assert response.json()["total"] == 1


@pytest.mark.asyncio
async def test_search_matches_creator_names(client_factory):
    async with client_factory() as client:
        await _create(client, title="Show A", creator_names="Distinctive Creator")
        await _create(client, title="Show B")
        response = await client.get("/api/v1/productions", params={"search": "distinctive creator"})

    assert response.json()["total"] == 1


@pytest.mark.asyncio
async def test_search_matches_company_name(client_factory):
    async with client_factory() as client:
        await _create(client, title="Show A", company_name="Distinctive Company")
        await _create(client, title="Show B")
        response = await client.get("/api/v1/productions", params={"search": "distinctive company"})

    assert response.json()["total"] == 1


@pytest.mark.asyncio
async def test_search_matches_director_name(client_factory):
    async with client_factory() as client:
        await _create(client, title="Show A", director_name="Distinctive Director")
        await _create(client, title="Show B")
        response = await client.get(
            "/api/v1/productions", params={"search": "distinctive director"}
        )

    assert response.json()["total"] == 1


@pytest.mark.asyncio
async def test_search_matches_venue_name(client_factory):
    async with client_factory() as client:
        await _create(client, title="Show A", venue_name="Distinctive Venue")
        await _create(client, title="Show B")
        response = await client.get("/api/v1/productions", params={"search": "distinctive venue"})

    assert response.json()["total"] == 1


@pytest.mark.asyncio
async def test_search_matches_city(client_factory):
    async with client_factory() as client:
        await _create(client, title="Show A", city="Distinctivetown")
        await _create(client, title="Show B")
        response = await client.get("/api/v1/productions", params={"search": "distinctivetown"})

    assert response.json()["total"] == 1


@pytest.mark.asyncio
async def test_filter_by_country_code(client_factory):
    async with client_factory() as client:
        await _create(client, title="German Show", country_code="DE")
        await _create(client, title="French Show", country_code="FR")
        response = await client.get("/api/v1/productions", params={"country_code": "de"})

    body = response.json()
    assert body["total"] == 1
    assert body["items"][0]["title"] == "German Show"


@pytest.mark.asyncio
async def test_filter_by_premiere_and_closing_date_range(client_factory):
    async with client_factory() as client:
        await _create(
            client, title="In Range", premiere_date="2026-01-10", closing_date="2026-01-20"
        )
        await _create(
            client, title="Out Of Range", premiere_date="2026-06-01", closing_date="2026-06-10"
        )
        await _create(client, title="Undated Show")

        response = await client.get(
            "/api/v1/productions",
            params={"from_date": "2026-01-01", "to_date": "2026-02-01"},
        )

    body = response.json()
    assert body["total"] == 1
    assert body["items"][0]["title"] == "In Range"


@pytest.mark.asyncio
async def test_open_ended_run_matches_from_date_only_filter(client_factory):
    async with client_factory() as client:
        await _create(client, title="Ongoing Show", premiere_date="2026-01-01", closing_date=None)
        response = await client.get("/api/v1/productions", params={"from_date": "2026-06-01"})

    body = response.json()
    assert body["total"] == 1
    assert body["items"][0]["title"] == "Ongoing Show"


# --- Pagination and ordering -----------------------------------------------


@pytest.mark.asyncio
async def test_pagination_total_limit_offset(client_factory):
    async with client_factory() as client:
        for i in range(5):
            await _create(client, title=f"Paginated Show {i}")

        first_page = await client.get("/api/v1/productions", params={"limit": 2, "offset": 0})
        second_page = await client.get("/api/v1/productions", params={"limit": 2, "offset": 2})

    assert first_page.json()["total"] == 5
    assert len(first_page.json()["items"]) == 2
    assert first_page.json()["limit"] == 2
    assert first_page.json()["offset"] == 0

    assert len(second_page.json()["items"]) == 2
    assert second_page.json()["offset"] == 2

    first_ids = {item["id"] for item in first_page.json()["items"]}
    second_ids = {item["id"] for item in second_page.json()["items"]}
    assert first_ids.isdisjoint(second_ids)


@pytest.mark.asyncio
async def test_list_is_ordered_by_title_ascending(client_factory):
    async with client_factory() as client:
        await _create(client, title="Zeta Show")
        await _create(client, title="Alpha Show")
        await _create(client, title="Mu Show")
        response = await client.get("/api/v1/productions")

    titles = [item["title"] for item in response.json()["items"]]
    assert titles == sorted(titles)


@pytest.mark.asyncio
async def test_duplicate_titles_break_ties_by_id_ascending(client_factory):
    async with client_factory() as client:
        first = await _create(client, title="Same Title", slug="same-title-1")
        second = await _create(client, title="Same Title", slug="same-title-2")
        response = await client.get("/api/v1/productions")

    items = [item for item in response.json()["items"] if item["title"] == "Same Title"]
    assert len(items) == 2
    expected_order = sorted([first["id"], second["id"]])
    assert [item["id"] for item in items] == expected_order


# --- Transactions -----------------------------------------------------------


@pytest.mark.asyncio
async def test_failed_create_does_not_leave_partial_data(client_factory):
    async with client_factory() as client:
        await _create(client, title="Existing", slug="taken-slug")
        failed = await client.post(
            "/api/v1/productions", json={"title": "New Attempt", "slug": "taken-slug"}
        )
        listing = await client.get("/api/v1/productions")

    assert failed.status_code == 409
    assert listing.json()["total"] == 1


@pytest.mark.asyncio
async def test_session_remains_usable_after_integrity_error(client_factory):
    """After a rolled-back IntegrityError, the same request-scoped session
    (and the app as a whole) must still be able to serve further requests
    without leftover broken transaction state.
    """

    async with client_factory() as client:
        await _create(client, title="First", slug="dup-check")
        conflict = await client.post(
            "/api/v1/productions", json={"title": "Second", "slug": "dup-check"}
        )
        assert conflict.status_code == 409

        # A subsequent, unrelated request must succeed normally.
        follow_up = await client.post("/api/v1/productions", json={"title": "Perfectly Fine"})
        assert follow_up.status_code == 201


# --- Seed data ---------------------------------------------------------------


@pytest.mark.asyncio
async def test_seed_command_is_idempotent_and_covers_required_variety():
    from app.db.seed import seed

    await seed()
    await seed()  # running twice must not create duplicates

    from sqlalchemy import select

    from app.db.session import async_session_factory
    from app.models.production import Production

    async with async_session_factory() as session:
        result = await session.execute(select(Production))
        productions = result.scalars().all()

    assert len(productions) >= 12
    assert any(p.work_title is not None for p in productions)
    assert any(p.work_title is None for p in productions)
    assert any(p.venue_name is not None for p in productions)
    assert any(p.venue_name is None for p in productions)
